### ISSUE TITLE
1.8.8 release date is wrong

### ISSUE THREAD

**Issue by Phoenix616** [stefvanschie/mc-versions-info.github.io#7]
1.8.8 was released on 2015-07-27, not 28: https://www.mojang.com/2015/07/minecraft-1-8-8-release/

https://github.com/stefvanschie/mc-versions-info.github.io/blob/44eed5c592dfb0417985394d7e265730c8d24e87/main.js#L30

**Comment by stefvanschie** [comment]
Thank you, this should now be fixed.
